### ISSUE TITLE
Change the name of the component to {{google-viewer}}

### ISSUE THREAD

**Issue by san650** [ntgussoni/ember-cli-google-viewer#2]
I think its a good practice to name the addon `ember-cli-foo` and use `foo` as the name of the exported component.

You can see [ember-power-select](https://github.com/cibernox/ember-power-select) as an example.

Maybe a good approach would be to export the component under the two names and print a deprecation warning when `{{ember-cli-google-viewer}}` is used.

**Comment by ntgussoni** [comment]
I like the idea!  Will try to make the changes soon 👍
